# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  nginxSourceFolder: 'nginx-fpm/0.4/'
  nginxImageName: 'nginx-fpm:$(build.buildId)'
 
steps:
- task: CopyFiles@2
  displayName: 'Copy nginx Dockerfiles to: $(build.sourcesdirectory)'
  inputs:
    SourceFolder: '$(nginxSourceFolder)'
    Contents: '*'
    TargetFolder: '$(build.sourcesdirectory)'
 
- script: docker build -f Dockerfile -t $(nginxImageName) .
  displayName: 'nginx docker build'
